 Insert Into tb_estado (uf_id,uf_nome) Values('AC','Acre');  
 Insert Into tb_estado (uf_id,uf_nome) Values('AL','Alagoas');  
 Insert Into tb_estado (uf_id,uf_nome) Values('AM','Amazonas');
 Insert Into tb_estado (uf_id,uf_nome) Values('AP','Amapá');
 Insert Into tb_estado (uf_id,uf_nome) Values('BA','Bahia');
 Insert Into tb_estado (uf_id,uf_nome) Values('CE','Ceará');
 Insert Into tb_estado (uf_id,uf_nome) Values('DF','Distrito Federal');
 Insert Into tb_estado (uf_id,uf_nome) Values('ES','Espírito Santo');
 Insert Into tb_estado (uf_id,uf_nome) Values('GO','Goiás');
 Insert Into tb_estado (uf_id,uf_nome) Values('MA','Maranhão');
 Insert Into tb_estado (uf_id,uf_nome) Values('MG','Minas Gerais');
 Insert Into tb_estado (uf_id,uf_nome) Values('MS','Mato Grosso do Sul');
 Insert Into tb_estado (uf_id,uf_nome) Values('MT','Mato Grosso');
 Insert Into tb_estado (uf_id,uf_nome) Values('PA','Pará');
 Insert Into tb_estado (uf_id,uf_nome) Values('PB','Paraíba');
 Insert Into tb_estado (uf_id,uf_nome) Values('PE','Pernambuco');
 Insert Into tb_estado (uf_id,uf_nome) Values('PI','Piauí');
 Insert Into tb_estado (uf_id,uf_nome) Values('PR','Paraná');
 Insert Into tb_estado (uf_id,uf_nome) Values('RJ','Rio de Janeiro');
 Insert Into tb_estado (uf_id,uf_nome) Values('RN','Rio Grande do Norte');
 Insert Into tb_estado (uf_id,uf_nome) Values('RO','Rondônia');
 Insert Into tb_estado (uf_id,uf_nome) Values('RR','Roraima');
 Insert Into tb_estado (uf_id,uf_nome) Values('RS','Rio Grande do Sul');
 Insert Into tb_estado (uf_id,uf_nome) Values('SC','Santa Catarina');
 Insert Into tb_estado (uf_id,uf_nome) Values('SE','Sergipe');
 Insert Into tb_estado (uf_id,uf_nome) Values('SP','São Paulo');
 Insert Into tb_estado (uf_id,uf_nome) Values('TO','Tocantins');